version: "3.7"

services:
  iot-frontend:
    build: frontend
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
      # Custom php.ini
      - ./docker/php/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini

  iot-backend:
    build: backend
    ports:
      - 21080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
      # Custom php.ini
      - ./docker/php/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini

  iot-api:
    build: api
    ports:
      - 22080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
      # Custom php.ini
      - ./docker/php/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini

  # Use Postgresql for DB
  db:
    image: postgres:16.1-alpine3.17
    ports:
      - "5433:5432"
    volumes:
      - ./docker/postgresql/conf:/etc/postgresql/
      - ./datadb:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
# volumes:
#   pgsql-data:
